### ISSUE TITLE
Can you please upgrade to latest version

### ISSUE THREAD

**Issue by nimatrazmjo** [LukasMarx/AngularUniversalGuide#1]
Hi,

Since there are a lot of changes in angular 6 and universal.

Can you please help me out. or at least update your repository to latest versions.

**Comment by LukasMarx** [comment]
Upgraded to angular 6.1 in 25c58a727c8f62b81eedd2fea313ea130964cd8b. 
Master is now on angular 6.1.
There is a legacy branch for angular 5.0 if someone still needs it.
