### ISSUE TITLE
update version angular 7

### ISSUE THREAD

**Issue by luisestebanvera** [LukasMarx/AngularUniversalGuide#2]
Hi,

Since there are a lot of changes in angular 7 and universal.

Can you please help me out. or at least update your repository to latest versions.

**Comment by LukasMarx** [comment]
Updated to Angular 7 in 2fb83b24bcd00c10eae5f2bf28d608320e6a9abe!

After all, the code did not change compared to the angular 6 version. Is there any speciffic problem?
